/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AIConfigDialog: typeof import('./src/components/AIChat/AIConfigDialog.vue')['default']
    AppSidebar: typeof import('./src/components/layout/AppSidebar.vue')['default']
    AppStatusBar: typeof import('./src/components/layout/AppStatusBar.vue')['default']
    AppTitleBar: typeof import('./src/components/layout/AppTitleBar.vue')['default']
    CommandTranslateDialog: typeof import('./src/components/AIChat/CommandTranslateDialog.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElLoading: typeof import('element-plus/es')['ElLoading']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTag: typeof import('element-plus/es')['ElTag']
    FileBrowser: typeof import('./src/components/FileTransfer/FileBrowser.vue')['default']
    FilePropertiesDialog: typeof import('./src/components/FileTransfer/FilePropertiesDialog.vue')['default']
    MessageItem: typeof import('./src/components/AIChat/MessageItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatCard: typeof import('./src/components/common/StatCard.vue')['default']
    TransferConfirmDialog: typeof import('./src/components/FileTransfer/TransferConfirmDialog.vue')['default']
    TransferHistoryDialog: typeof import('./src/components/FileTransfer/TransferHistoryDialog.vue')['default']
    TransferItem: typeof import('./src/components/FileTransfer/TransferItem.vue')['default']
    TransferSettingsDialog: typeof import('./src/components/FileTransfer/TransferSettingsDialog.vue')['default']
    UsageStatsDialog: typeof import('./src/components/AIChat/UsageStatsDialog.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
